"""empty message

Revision ID: 9a9da09a2683
Revises: 51d01388e299
Create Date: 2022-04-04 01:20:30.199145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9da09a2683'
down_revision = '51d01388e299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'desc',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'desc',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
